// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// _CVI_create
SEXP _CVI_create(Rcpp::String type, NumericMatrix X, int K, bool allow_undo);
RcppExport SEXP _CVI__CVI_create(SEXP typeSEXP, SEXP XSEXP, SEXP KSEXP, SEXP allow_undoSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::String >::type type(typeSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    Rcpp::traits::input_parameter< bool >::type allow_undo(allow_undoSEXP);
    rcpp_result_gen = Rcpp::wrap(_CVI_create(type, X, K, allow_undo));
    return rcpp_result_gen;
END_RCPP
}
// _CVI_set_labels
void _CVI_set_labels(SEXP cvi_ptr, NumericVector y);
RcppExport SEXP _CVI__CVI_set_labels(SEXP cvi_ptrSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type cvi_ptr(cvi_ptrSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    _CVI_set_labels(cvi_ptr, y);
    return R_NilValue;
END_RCPP
}
// _CVI_compute
double _CVI_compute(SEXP cvi_ptr);
RcppExport SEXP _CVI__CVI_compute(SEXP cvi_ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type cvi_ptr(cvi_ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(_CVI_compute(cvi_ptr));
    return rcpp_result_gen;
END_RCPP
}
// _CVI_undo
void _CVI_undo(SEXP cvi_ptr);
RcppExport SEXP _CVI__CVI_undo(SEXP cvi_ptrSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type cvi_ptr(cvi_ptrSEXP);
    _CVI_undo(cvi_ptr);
    return R_NilValue;
END_RCPP
}
// _CVI_modify
void _CVI_modify(SEXP cvi_ptr, int i, int j);
RcppExport SEXP _CVI__CVI_modify(SEXP cvi_ptrSEXP, SEXP iSEXP, SEXP jSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type cvi_ptr(cvi_ptrSEXP);
    Rcpp::traits::input_parameter< int >::type i(iSEXP);
    Rcpp::traits::input_parameter< int >::type j(jSEXP);
    _CVI_modify(cvi_ptr, i, j);
    return R_NilValue;
END_RCPP
}
// CVI_CalinskiHarabasz
double CVI_CalinskiHarabasz(NumericMatrix X, NumericVector y, int K);
RcppExport SEXP _CVI_CVI_CalinskiHarabasz(SEXP XSEXP, SEXP ySEXP, SEXP KSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    rcpp_result_gen = Rcpp::wrap(CVI_CalinskiHarabasz(X, y, K));
    return rcpp_result_gen;
END_RCPP
}
// CVI_WCSS
double CVI_WCSS(NumericMatrix X, NumericVector y, int K);
RcppExport SEXP _CVI_CVI_WCSS(SEXP XSEXP, SEXP ySEXP, SEXP KSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    rcpp_result_gen = Rcpp::wrap(CVI_WCSS(X, y, K));
    return rcpp_result_gen;
END_RCPP
}
// CVI_BallHall
double CVI_BallHall(NumericMatrix X, NumericVector y, int K);
RcppExport SEXP _CVI_CVI_BallHall(SEXP XSEXP, SEXP ySEXP, SEXP KSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    rcpp_result_gen = Rcpp::wrap(CVI_BallHall(X, y, K));
    return rcpp_result_gen;
END_RCPP
}
// CVI_Gamma
double CVI_Gamma(NumericMatrix X, NumericVector y, int K);
RcppExport SEXP _CVI_CVI_Gamma(SEXP XSEXP, SEXP ySEXP, SEXP KSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    rcpp_result_gen = Rcpp::wrap(CVI_Gamma(X, y, K));
    return rcpp_result_gen;
END_RCPP
}
// CVI_DaviesBouldin
double CVI_DaviesBouldin(NumericMatrix X, NumericVector y, int K);
RcppExport SEXP _CVI_CVI_DaviesBouldin(SEXP XSEXP, SEXP ySEXP, SEXP KSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    rcpp_result_gen = Rcpp::wrap(CVI_DaviesBouldin(X, y, K));
    return rcpp_result_gen;
END_RCPP
}
// CVI_Silhouette
double CVI_Silhouette(NumericMatrix X, NumericVector y, int K);
RcppExport SEXP _CVI_CVI_Silhouette(SEXP XSEXP, SEXP ySEXP, SEXP KSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    rcpp_result_gen = Rcpp::wrap(CVI_Silhouette(X, y, K));
    return rcpp_result_gen;
END_RCPP
}
// CVI_SilhouetteW
double CVI_SilhouetteW(NumericMatrix X, NumericVector y, int K);
RcppExport SEXP _CVI_CVI_SilhouetteW(SEXP XSEXP, SEXP ySEXP, SEXP KSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    rcpp_result_gen = Rcpp::wrap(CVI_SilhouetteW(X, y, K));
    return rcpp_result_gen;
END_RCPP
}
// CVI_Dunn
double CVI_Dunn(NumericMatrix X, NumericVector y, int K);
RcppExport SEXP _CVI_CVI_Dunn(SEXP XSEXP, SEXP ySEXP, SEXP KSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    rcpp_result_gen = Rcpp::wrap(CVI_Dunn(X, y, K));
    return rcpp_result_gen;
END_RCPP
}
// CVI_GDunn
double CVI_GDunn(NumericMatrix X, NumericVector y, int K, int lowercaseDelta, int uppercaseDelta);
RcppExport SEXP _CVI_CVI_GDunn(SEXP XSEXP, SEXP ySEXP, SEXP KSEXP, SEXP lowercaseDeltaSEXP, SEXP uppercaseDeltaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    Rcpp::traits::input_parameter< int >::type lowercaseDelta(lowercaseDeltaSEXP);
    Rcpp::traits::input_parameter< int >::type uppercaseDelta(uppercaseDeltaSEXP);
    rcpp_result_gen = Rcpp::wrap(CVI_GDunn(X, y, K, lowercaseDelta, uppercaseDelta));
    return rcpp_result_gen;
END_RCPP
}
// CVI_WCNN
double CVI_WCNN(NumericMatrix X, NumericVector y, int K, int M);
RcppExport SEXP _CVI_CVI_WCNN(SEXP XSEXP, SEXP ySEXP, SEXP KSEXP, SEXP MSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    Rcpp::traits::input_parameter< int >::type M(MSEXP);
    rcpp_result_gen = Rcpp::wrap(CVI_WCNN(X, y, K, M));
    return rcpp_result_gen;
END_RCPP
}
// CVI_DuNNOWA
double CVI_DuNNOWA(NumericMatrix X, NumericVector y, int K, int M, Rcpp::String owa_numerator, Rcpp::String owa_denominator);
RcppExport SEXP _CVI_CVI_DuNNOWA(SEXP XSEXP, SEXP ySEXP, SEXP KSEXP, SEXP MSEXP, SEXP owa_numeratorSEXP, SEXP owa_denominatorSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    Rcpp::traits::input_parameter< int >::type M(MSEXP);
    Rcpp::traits::input_parameter< Rcpp::String >::type owa_numerator(owa_numeratorSEXP);
    Rcpp::traits::input_parameter< Rcpp::String >::type owa_denominator(owa_denominatorSEXP);
    rcpp_result_gen = Rcpp::wrap(CVI_DuNNOWA(X, y, K, M, owa_numerator, owa_denominator));
    return rcpp_result_gen;
END_RCPP
}
// _CVI_improve
List _CVI_improve(SEXP cvi_ptr, NumericVector y0, bool allow_revisit, int max_iter_with_no_improvement, int max_iter, int max_samples, bool verbose);
RcppExport SEXP _CVI__CVI_improve(SEXP cvi_ptrSEXP, SEXP y0SEXP, SEXP allow_revisitSEXP, SEXP max_iter_with_no_improvementSEXP, SEXP max_iterSEXP, SEXP max_samplesSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type cvi_ptr(cvi_ptrSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y0(y0SEXP);
    Rcpp::traits::input_parameter< bool >::type allow_revisit(allow_revisitSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter_with_no_improvement(max_iter_with_no_improvementSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< int >::type max_samples(max_samplesSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(_CVI_improve(cvi_ptr, y0, allow_revisit, max_iter_with_no_improvement, max_iter, max_samples, verbose));
    return rcpp_result_gen;
END_RCPP
}
// _CVI_improve_turbo
List _CVI_improve_turbo(SEXP cvi_ptr, NumericMatrix Y0, int max_iter_with_no_improvement, int max_iter, bool verbose);
RcppExport SEXP _CVI__CVI_improve_turbo(SEXP cvi_ptrSEXP, SEXP Y0SEXP, SEXP max_iter_with_no_improvementSEXP, SEXP max_iterSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type cvi_ptr(cvi_ptrSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Y0(Y0SEXP);
    Rcpp::traits::input_parameter< int >::type max_iter_with_no_improvement(max_iter_with_no_improvementSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(_CVI_improve_turbo(cvi_ptr, Y0, max_iter_with_no_improvement, max_iter, verbose));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_CVI__CVI_create", (DL_FUNC) &_CVI__CVI_create, 4},
    {"_CVI__CVI_set_labels", (DL_FUNC) &_CVI__CVI_set_labels, 2},
    {"_CVI__CVI_compute", (DL_FUNC) &_CVI__CVI_compute, 1},
    {"_CVI__CVI_undo", (DL_FUNC) &_CVI__CVI_undo, 1},
    {"_CVI__CVI_modify", (DL_FUNC) &_CVI__CVI_modify, 3},
    {"_CVI_CVI_CalinskiHarabasz", (DL_FUNC) &_CVI_CVI_CalinskiHarabasz, 3},
    {"_CVI_CVI_WCSS", (DL_FUNC) &_CVI_CVI_WCSS, 3},
    {"_CVI_CVI_BallHall", (DL_FUNC) &_CVI_CVI_BallHall, 3},
    {"_CVI_CVI_Gamma", (DL_FUNC) &_CVI_CVI_Gamma, 3},
    {"_CVI_CVI_DaviesBouldin", (DL_FUNC) &_CVI_CVI_DaviesBouldin, 3},
    {"_CVI_CVI_Silhouette", (DL_FUNC) &_CVI_CVI_Silhouette, 3},
    {"_CVI_CVI_SilhouetteW", (DL_FUNC) &_CVI_CVI_SilhouetteW, 3},
    {"_CVI_CVI_Dunn", (DL_FUNC) &_CVI_CVI_Dunn, 3},
    {"_CVI_CVI_GDunn", (DL_FUNC) &_CVI_CVI_GDunn, 5},
    {"_CVI_CVI_WCNN", (DL_FUNC) &_CVI_CVI_WCNN, 4},
    {"_CVI_CVI_DuNNOWA", (DL_FUNC) &_CVI_CVI_DuNNOWA, 6},
    {"_CVI__CVI_improve", (DL_FUNC) &_CVI__CVI_improve, 7},
    {"_CVI__CVI_improve_turbo", (DL_FUNC) &_CVI__CVI_improve_turbo, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_CVI(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
